:sectnums: 
:toc: auto

= Noise Measurement

== Aim of the project

The aim of this project is to build a device that will measure and report in real time the noise level of the room where it was installed.

The initial idea behind this project was to measure the noise level in an house/living room where childrens could make a lot of noise ... but it can also be used in a workplace/openspace if you've some noisy colleagues.


=== Main ideas

The device must run 24/24 7/7. It measure the noise level and visually report it using RGB leds. +
RGB leds color will be based on the noise level. For exemple, we can imagine the following configuration:

[cols="^1,^1,5"]
|===
^| **Color**    ^| **Decibel range**    ^| **Meaning**
 | GREEN         | [0,50db[              | Quiet space
 | ORANGE        | [50db, 60db[          | Normal sound level for a working place 
 | RED           | [60db, [              | Noise level too hight ... need to more calm
|===

[NOTE]
====
It could be insterresting to have values related to human health.
====


=== Project needs

* basic needs
** low cost 
** visualization of the noise level
* advanced needs
** wifi connection to report noise measure
** ???  




== Solution's design

=== Prototype

To make a prototype we've targetted an link:https://docs.arduino.cc/hardware/nano-33-ble-sense[**Arduino Nano 33 BLE Sense**].

This board is :

* (too) costly for the final target
* embed a lot of unneeded components

but it'll allow to make a first / basic prototype really easily.

The microphone on the board is an **MP34DT05** that work on **PDM mode**.


==== NoiseMeasurement serial plotter

This first part will focus on the noise measurement part. We'll simply ouput the result using the serial plotter to show the result. 

#TODO: Add code details#


==== NoiseMeasurement RGB led

This second part will complete the serial outpu with a RGB led display system. Instead of using the onboard led that is not really clearly visible, we'll use an additionnal led.

#TODO: Add code details#

==== What next ?

Now that we have made a basic prototype we can go deeper in the final project.

* must we go deeper in noise level calculation ?
* what feature did we want to add ? (Wifi)
* what design does we need ? 



