:sectnums: 
:toc: auto

= Noise Measurement

== Aim of the project

The aim of this project is to build a device that will measure and report in real time the noise level of the room where it was installed.

The initial idea behind this project was to measure the noise level in an house/living room where childrens could make a lot of noise ... but it can also be used in a workplace/openspace if you've some noisy colleagues.


=== Main ideas

The device must run 24/24 7/7. It measure the noise level and visually report it using RGB leds. +
RGB leds color will be based on the noise level:

[cols="^1,^1,5"]
|===
^| **Color**    ^| **Decibel range**    ^| **Meaning**
 | GREEN         | [0,50db[              | Quiet space
 | ORANGE        | [50db, 60db[          | Normal sound level for a working place 
 | RED           | [60db, [              | Noise level too hight ... need to more calm
|===



=== Project needs

* basic needs
** low cost 
** visualization of the noise level
* advanced needs
** wifi connection to report noise measure
** ???  



== Solution's design

=== Prototype

To make a prototype we can target an link:https://docs.arduino.cc/hardware/nano-33-ble-sense[**Arduino Nano 33 BLE Sense**].

This board is :

* (too) costly for the final target
* embed a lot of unneeded components


But it'll allow too easily make a first / basic prototype.

The microphone on the board is an **MP34DT05**.




=== Target solution - V1

